version: "3"
services:
  front-prod-container:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - "3001:80"
    # volumes:
    #   - ./src:/app/src
    # environment:
    #   - REACT_APP_NAME=crud
    #   - CHOKIDAR_USEPOLLING=true